using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.Sponsor.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class CustomsTab : Control, SponsorEui.ISponsorEui
{
    public CustomsTab()
    {
        RobustXamlLoader.Load(this);
    }

    private SponsorEui? currentEui;

    public void SetEui(SponsorEui currentEui)
    {
        this.currentEui = currentEui;
    }
}
