using System.Linq;
using Content.Client.DeadSpace.Sponsor.UI.Controls;
using Content.Shared.DeadSpace.Sponsor;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.Sponsor.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class GeneralTab : Control, SponsorEui.ISponsorEui
{
    public GeneralTab()
    {
        RobustXamlLoader.Load(this);
    }

    private SponsorEui? currentEui;

    public void SetEui(SponsorEui currentEui)
    {
        this.currentEui = currentEui;
        OnCalendarButtonPressed += OnOnCalendarButtonPressed;
    }

    private readonly TimeOnly ZeroTimeOnly = TimeOnly.FromTimeSpan(TimeSpan.Zero);

    private void OnOnCalendarButtonPressed(BaseButton.ButtonEventArgs arg1, string arg2)
    {
        CalendarContainer.RemoveAllChildren();

        SponsorCalendar? calendar = null;
        if (_currentCalendar != string.Empty)
        {
            calendar = currentEui!.Calendars.FirstOrDefault(x => x.Name == _currentCalendar);
        }

        calendar ??= currentEui!.Calendars.First();

        var weeked = calendar.CalendarItems.GroupBy(x => new Week(x.Date.ToDateTime(ZeroTimeOnly)));

        foreach (var week in weeked)
        {
            var calendarRow = new SponsorCalendarRow(
                    calendar.Id,
                    week
                        .Select(x => x.Id)
                        .ToArray()
            );
            calendarRow.SetEui(currentEui!);
            calendarRow.UpdateCalendar();
            CalendarContainer.AddChild(calendarRow);
        }
    }

    public void UpdateCalendar()
    {
        PopulateCalendarsButtons();
    }

    private sealed class CalendarButton : Button
    {
        public string? Id;
    }

    public event Action<BaseButton.ButtonEventArgs, string>? OnCalendarButtonPressed;

    private string _currentCalendar = string.Empty;

    private void PopulateCalendarsButtons()
    {
        var allCalendarNames = new List<string>();
        foreach (var listing in currentEui!.Calendars.Select(x => x.Name).Distinct())
        {
            allCalendarNames.Add(listing);
        }

        allCalendarNames = allCalendarNames.OrderBy(c => c).ToList();

        // This will reset the Current Category selection if nothing matches the search.
        if (allCalendarNames.All(category => category != _currentCalendar))
            _currentCalendar = string.Empty;

        if (_currentCalendar == string.Empty && allCalendarNames.Count > 0)
            _currentCalendar = allCalendarNames.First();

        CalendarList.Children.Clear();
        if (allCalendarNames.Count < 1)
        {
            CalendarList.Visible = false;
        }

        var group = new ButtonGroup();
        foreach (var proto in allCalendarNames)
        {
            var catButton = new CalendarButton()
            {
                Text = proto,
                Id = proto,
                Pressed = proto == _currentCalendar,
                Group = group,
                ToggleMode = true,
                StyleClasses = { "OpenBoth" }
            };

            catButton.OnPressed += args => OnCalendarButtonPressed?.Invoke(args, catButton.Id);
            CalendarList.AddChild(catButton);
        }
    }
}
