using System.Linq;
using Content.Client.DeadSpace.Sponsor.UI.Controls;
using Content.Shared.DeadSpace.Sponsor;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.Sponsor.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class GeneralTab : Control, SponsorEui.ISponsorEui
{
    public GeneralTab()
    {
        RobustXamlLoader.Load(this);
    }

    private SponsorEui? currentEui;

    public void SetEui(SponsorEui currentEui)
    {
        this.currentEui = currentEui;
        OnCalendarButtonPressed += OnOnCalendarButtonPressed;
    }

    private int GetDayOfWeek(DateTime date)
    {
        var d = date.Day;
        var m = date.Month;
        var y = date.Year;

        if (m < 3)
        {
            m += 12;
            y--;
        }

        var h = (d + (13 * (m + 1)) / 5 + y + y / 4 - y / 100 + y / 400) % 7;
        return (h + 5) % 7;
    }

    private int GetWeekOfYear(DateTime date)
    {
        int dayOfWeek = GetDayOfWeek(date);
        var thursday = date.AddDays(3 - dayOfWeek);
        var jan1 = new DateTime(thursday.Year, 1, 1);
        var days = (thursday - jan1).Days;
        return (days / 7) + 1;
    }

    private void OnOnCalendarButtonPressed(BaseButton.ButtonEventArgs? arg1, string arg2)
    {
        CalendarContainer.RemoveAllChildren();

        var calendar = _currentCalendar != string.Empty
            ? currentEui!.Calendars.FirstOrDefault(x => x.Name == _currentCalendar)
            : currentEui!.Calendars.FirstOrDefault();

        if (calendar == null)
        {
            return;
        }

        var byWeeks = calendar.CalendarItems
            .GroupBy(item => GetWeekOfYear(item.Date))
            .OrderBy(x => x.Key)
            .ToDictionary(g => g.Key, g => g.ToList());

        foreach (var week in byWeeks)
        {
            var calendarRow = new SponsorCalendarRow(
                calendar.Id,
                week.Value.Select(x => x.Id).ToArray(),
                week.Key
            );
            calendarRow.SetEui(currentEui!);
            calendarRow.UpdateCalendar();
            CalendarContainer.AddChild(calendarRow);
        }
    }

    public void UpdateCalendar()
    {
        PopulateCalendarsButtons();
    }

    private sealed class CalendarButton : Button
    {
        public string? Id;
    }

    public event Action<BaseButton.ButtonEventArgs?, string>? OnCalendarButtonPressed;

    private string _currentCalendar = string.Empty;

    private void PopulateCalendarsButtons()
    {
        var allCalendarNames = currentEui!.Calendars.Select(x => x.Name).Distinct().Order().ToList();

        if (allCalendarNames.All(category => category != _currentCalendar))
            _currentCalendar = string.Empty;

        if (_currentCalendar == string.Empty && allCalendarNames.Count > 0)
        {
            _currentCalendar = allCalendarNames.First();
        }

        CalendarList.Children.Clear();
        if (allCalendarNames.Count < 2)
        {
            CalendarList.Visible = false;
        }

        var group = new ButtonGroup();
        foreach (var proto in allCalendarNames)
        {
            var catButton = new CalendarButton()
            {
                Text = proto,
                Id = proto,
                Pressed = proto == _currentCalendar,
                Group = group,
                ToggleMode = true,
                StyleClasses = { "OpenBoth" }
            };

            catButton.OnPressed += args => OnCalendarButtonPressed?.Invoke(args, catButton.Id);
            CalendarList.AddChild(catButton);
        }

        OnCalendarButtonPressed?.Invoke(null, string.Empty);
    }
}
