using System.Linq;
using Content.Client.DeadSpace.Sponsor.UI.Controls;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.Sponsor.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class ItemsTab : Control, SponsorEui.ISponsorEui
{
    public ItemsTab()
    {
        RobustXamlLoader.Load(this);
    }

    private SponsorEui? currentEui;

    public void SetEui(SponsorEui currentEui)
    {
        this.currentEui = currentEui;

        OnCategoryButtonPressed += OnOnCategoryButtonPressed;
    }

    private void OnOnCategoryButtonPressed(BaseButton.ButtonEventArgs arg1, string arg2)
    {
        _currentCategory = arg2;
        UpdateItems();
    }

    private sealed class StoreCategoryButton : Button
    {
        public string? Id;
    }

    public event Action<BaseButton.ButtonEventArgs, string>? OnCategoryButtonPressed;

    private string _currentCategory = string.Empty;
    private void PopulateStoreCategoryButtons()
    {
        var allCategories = new List<string>();
        foreach (var listing in currentEui!.Catalog.Select(x=>x.CategoryName).Distinct())
        {
            allCategories.Add(listing);
        }

        allCategories = allCategories.OrderBy(c => c).ToList();

        // This will reset the Current Category selection if nothing matches the search.
        if (allCategories.All(category => category != _currentCategory))
            _currentCategory = string.Empty;

        if (_currentCategory == string.Empty && allCategories.Count > 0)
            _currentCategory = allCategories.First();

        CategoryListContainer.Children.Clear();
        if (allCategories.Count < 1)
            return;

        var group = new ButtonGroup();
        foreach (var proto in allCategories)
        {
            var catButton = new StoreCategoryButton
            {
                Text = proto,
                Id = proto,
                Pressed = proto == _currentCategory,
                Group = group,
                ToggleMode = true,
                StyleClasses = { "OpenBoth" }
            };

            catButton.OnPressed += args => OnCategoryButtonPressed?.Invoke(args, catButton.Id);
            CategoryListContainer.AddChild(catButton);
        }
    }

    private void UpdateItems()
    {
        StoreListingsContainer.RemoveAllChildren();
        var q = currentEui!.Catalog.AsEnumerable();
        if (_currentCategory != string.Empty)
        {
            q = q.Where(x => x.CategoryName == _currentCategory);
        }
        foreach (var item in q)
        {
            var row = new SponsorItemRow(item.Id);
            row.SetEui(currentEui);
            row.UpdateCategory();
            row.UpdatePlayerInfo();
            StoreListingsContainer.AddChild(row);
        }
    }

    public void UpdateCategory()
    {
        CategoryListContainer.RemoveAllChildren();
        PopulateStoreCategoryButtons();
        UpdateItems();
    }

    public void UpdatePlayerInfo()
    {
        foreach (var control in StoreListingsContainer.Children)
        {
            if (control is not SponsorEui.ISponsorEui eui)
            {
                continue;
            }
            eui.UpdatePlayerInfo();
        }
    }
}
