using System.Linq;
using Content.Client.DeadSpace.Sponsor.UI.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.Sponsor.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class SubsTab : Control, SponsorEui.ISponsorEui
{
    public SubsTab()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void EnteredTree()
    {
        var playeritems = currentEui!.PlayerInfo.RentItems;
        foreach (var item in playeritems)
        {
            var row = new SponsorItemRow(item.ItemId, true);
            row.SetEui(currentEui);
            StoreListingsContainer.AddChild(row);
        }
    }

    protected override void ExitedTree()
    {
        StoreListingsContainer.RemoveAllChildren();
    }

    private SponsorEui? currentEui;

    public void SetEui(SponsorEui currentEui)
    {
        this.currentEui = currentEui;
    }

    public void UpdatePlayerInfo()
    {
        StoreListingsContainer.RemoveAllChildren();
        foreach (var rentItem in currentEui!.PlayerInfo.RentItems.DistinctBy(x => x.ItemId))
        {
            var row = new SponsorItemRow(rentItem.ItemId, true);
            row.SetEui(currentEui);
            row.UpdateCategory();
            row.UpdatePlayerInfo();
            StoreListingsContainer.AddChild(row);
        }
    }
}
