using System.Linq;
using Content.Client.Message;
using Content.Shared.DeadSpace.Sponsor;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.DeadSpace.Sponsor.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class SponsorCalendarItemView : Control, SponsorEui.ISponsorEui
{
    private readonly int _calendarItemId;
    private readonly int _calendarId;
    private SponsorEui _eui = default!;

    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;
    private SpriteSystem _spriteSystem = default!;

    private readonly ResPath CoinIcon = new("/Textures/_DeadSpace/Interface/Sponsor/coin.png");
    private readonly ResPath CrystalIcon = new("/Textures/_DeadSpace/Interface/Sponsor/crystal.png");

    public void SetEui(SponsorEui currentEui)
    {
        _eui = currentEui;
    }

    public SponsorCalendarItemView(int calendarItemId, int calendarId)
    {
        _calendarItemId = calendarItemId;
        _calendarId = calendarId;
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entityManager.System<SpriteSystem>();
    }

    public void UpdateCalendar()
    {
        var calendar = _eui.Calendars
            .First(x => x.Id == _calendarId);
        var calendarItem = calendar.CalendarItems
            .SelectMany(x => x.Value)
            .Single(x => x.Id == _calendarItemId);

        var item = calendarItem.Item;
        if (item != null)
        {
            if (item.GamePrototype != null && _proto.TryIndex(item.GamePrototype, out var entityPrototype))
            {
                ItemTexture.Visible = true;
                ItemTexture.Texture = _spriteSystem.Frame0(entityPrototype);
                ItemName.Text = entityPrototype.Name;
                ItemDescription.SetMarkup(entityPrototype.Description);
            }
            else
            {
                ItemTexture.Visible = false;
                ItemName.Text = item.Name;
                ItemDescription.SetMarkup("");
            }
        }
        else
        {
            ItemTexture.TexturePath = CrystalIcon.Filename;
            ItemName.Text = $"{calendarItem.Crystal} кристаллов";
        }


        var claimed = _eui.PlayerInfo.ClaimedCalendarItems.OrderBy(x => x.ClaimedDate).ToList();
        var claim = claimed.FirstOrDefault(x => x.CalendarItemId == calendarItem.Id);
        if (claim == null)
        {
            DateTaken.Visible = false;
            var lastClaimed = claimed.LastOrDefault();
            var items = calendar.CalendarItems.SelectMany(x => x.Value).OrderBy(x => x.Date).ToList();

            if (lastClaimed == null)
            {
                if (calendarItem.Date != DateTime.Today)
                {
                    GetButton.Disabled = true;
                }
            }
            else
            {
                var index = items.FindIndex(x => x.Id == lastClaimed.CalendarItemId);
                if (index + 1 < items.Count)
                {
                    if (calendarItem != items[index + 1])
                    {
                        GetButton.Text = calendarItem.Date.ToShortDateString();
                        GetButton.Disabled = true;
                    }
                    else
                    {
                        GetButton.Text = "Получить";
                    }
                }
            }

            GetButton.OnPressed += args =>
            {
                _eui.TryCalendarItem(_calendarId);
            };
        }
        else
        {
            DateTaken.Visible = true;
            DateTaken.Text = claim.ClaimedDate.ToShortDateString();

            GetButton.Text = "Уже получено";
            GetButton.Disabled = true;
        }
    }
}
