using System.Linq;
using Content.Client.Message;
using Content.Shared.DeadSpace.Sponsor;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.DeadSpace.Sponsor.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class SponsorItemRow : Control, SponsorEui.ISponsorEui
{
    private readonly int _itemId;
    private readonly bool _onlyPrint;

    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;
    private SpriteSystem _spriteSystem = default!;

    public SponsorItemRow(int itemId, bool onlyPrint = false)
    {
        _itemId = itemId;
        _onlyPrint = onlyPrint;
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entityManager.System<SpriteSystem>();
        StoreItemGetButton.OnPressed += StoreItemGetButtonOnOnPressed;
        BuyButton.OnPressed += BuyButtonOnOnPressed;
        Range.OnItemSelected += UpdateBuyButton;
        Currency.OnItemSelected += UpdateRanges;
    }


    private SponsorEui _eui = default!;

    public void SetEui(SponsorEui currentEui)
    {
        _eui = currentEui;
    }

    public void UpdatePlayerInfo()
    {
        var rent = _eui.PlayerInfo.RentItems.FirstOrDefault(x => x.ItemId == _itemId);
        SponsorItem? item = null;
        if (_onlyPrint)
        {
            var playerItem = _eui.PlayerInfo.RentItems.First(x => x.ItemId == _itemId);
            item = _eui.Catalog.FirstOrDefault(x => x.Id == playerItem.ItemId);
        }
        else
        {
            item = _eui.Catalog.Single(x => x.Id == _itemId);
        }

        if (rent != null && rent.ExpirationDate == null)
        {
            StoreItemGetButton.Text = $"Получить";
            DiscountSubText.Text = "Навсегда";
            RentButtons.Visible = false;
            return;
        }

        if (rent == null || rent.ExpirationDate.HasValue)
        {
            if (rent is { ExpirationDate: not null })
            {
                StoreItemGetButton.Text = $"Получить";
                DiscountSubText.Text = "Аренда до: " + rent.ExpirationDate.Value.ToString("g");
            }
            else
            {
                StoreItemGetButton.Visible = false;
            }

            Currency.Clear();
            Range.Clear();
            if (item!.Prices == null)
            {
                RentButtons.Visible = false;
                return;
            }

            int? currencyId = null;
            int? rangeId = null;

            if (item.Prices.TryGetValue(PriceType.Coin, out var coinPrices))
            {
                Currency.AddItem(Loc.GetString($"sponsor-currency-{Currency.SelectedId}"), (int)PriceType.Coin);
                currencyId ??= (int)PriceType.Coin;
                foreach (var coinPrice in coinPrices)
                {
                    var text = coinPrice.Days == -1 ? "бессрочно" : $"{coinPrice.Days} дней";
                    Range.AddItem(text, coinPrice.Days);
                    rangeId ??= coinPrice.Days;
                }
            }

            if (item.Prices.TryGetValue(PriceType.Crystal, out var crystalPrices))
            {
                Currency.AddItem(Loc.GetString($"sponsor-currency-{Currency.SelectedId}"), (int)PriceType.Crystal);
                currencyId ??= (int)PriceType.Crystal;
                foreach (var crystalPrice in crystalPrices)
                {
                    var text = crystalPrice.Days == -1 ? "бессрочно" : $"{crystalPrice.Days} дней";
                    Range.AddItem(text, crystalPrice.Days);
                    rangeId ??= crystalPrice.Days;
                }
            }

            if (currencyId.HasValue)
            {
                Currency.SelectId(currencyId.Value);
                UpdateRanges(null);
            }

            if (rangeId.HasValue)
            {
                Range.SelectId(rangeId.Value);
                UpdateBuyButton(null);
            }
        }
    }

    public void UpdateCategory()
    {
        var item = _eui.Catalog.Single(x => x.Id == _itemId);

        if (item.GamePrototype != null && _proto.TryIndex<EntityPrototype>(item.GamePrototype, out var entityPrototype))
        {
            StoreItemTexture.Visible = true;
            StoreItemTexture.Texture = _spriteSystem.Frame0(entityPrototype);
            StoreItemName.Text = entityPrototype.Name;
            StoreItemDescription.SetMarkup(entityPrototype.Description);
        }
        else
        {
            StoreItemTexture.Visible = false;
            StoreItemName.Text = item.Name;
            StoreItemDescription.SetMarkup("");
        }
    }

    private void StoreItemGetButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        _eui.GetButton(_eui.PlayerInfo.RentItems.First(x => x.ItemId == _itemId).Id);
    }

    private void BuyButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        _eui.BuyButton(_itemId, (PriceType)Currency.SelectedId, Range.SelectedId);
    }

    private void UpdateBuyButton(OptionButton.ItemSelectedEventArgs? obj)
    {
        if (obj != null)
            Range.SelectId(obj.Id);
        var item = _eui.Catalog.Single(x => x.Id == _itemId);
        var price = item.Prices![(PriceType)Currency.SelectedId].First(x => x.Days == Range.SelectedId).Price;
        BuyButton.Text = $"Купить за {price}";
    }

    private void UpdateRanges(OptionButton.ItemSelectedEventArgs? obj)
    {
        if (obj != null)
            Currency.SelectId(obj.Id);
        Range.Clear();
        var item = _eui.Catalog.Single(x => x.Id == _itemId);
        if (item.Prices == null)
            return;

        int? rangeId = null;

        if (item.Prices.TryGetValue((PriceType)Currency.SelectedId, out var prices))
        {
            foreach (var price in prices)
            {
                var text = price.Days == -1 ? "бессрочно" : $"{price.Days} дней";
                Range.AddItem(text, price.Days);
                rangeId ??= price.Days;
            }
        }

        if (rangeId.HasValue)
        {
            Range.SelectId(rangeId.Value);
            UpdateBuyButton(null);
        }
    }
}
