using System.Linq;
using Content.Shared.DeadSpace.Sponsor;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.DeadSpace.Sponsor.UI.Controls;

[GenerateTypedNameReferences]
public sealed partial class SponsorCalendarRow : Control, SponsorEui.ISponsorEui
{
    private readonly int _calendarId;
    private readonly int[] _itemIds;
    private readonly int _calendarNum;
    private SponsorEui _eui = default!;

    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;
    private SpriteSystem _spriteSystem = default!;

    public void SetEui(SponsorEui currentEui)
    {
        _eui = currentEui;
    }

    public SponsorCalendarRow(int calendarId, int[] itemIds, int calendarNum)
    {
        _calendarId = calendarId;
        _itemIds = itemIds;
        _calendarNum = calendarNum;
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entityManager.System<SpriteSystem>();
        WeekLabel.Text = $"Неделя {calendarNum}";
    }

    public void UpdateCalendar()
    {
        foreach (var calendarItem in _eui.Calendars.First(x => x.Id == _calendarId)
                     .CalendarItems
                     .Where(x => _itemIds.Contains(x.Id))
                     .OrderBy(x => x.Date))
        {
            var row = new SponsorCalendarItemView(calendarItem.Id, _calendarId);
            row.SetEui(_eui);
            row.UpdateCalendar();
            WeekScroller.AddChild(row);
        }
    }
}
