using System.Linq;
using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.DeadSpace.Sponsor.UI;

[GenerateTypedNameReferences]
public sealed partial class SponsorItemRow : Control, SponsorEui.ISponsorEui
{
    private readonly int _itemId;

    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;

    private SpriteSystem _spriteSystem = default!;

    public SponsorItemRow(int itemId, bool onlyPrint = false)
    {
        _itemId = itemId;
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entityManager.System<SpriteSystem>();
        StoreItemBuyButton.OnPressed += StoreItemBuyButtonOnOnPressed;
    }

    private SponsorEui _eui = default!;
    public void SetEui(SponsorEui currentEui)
    {
        _eui = currentEui;
    }

    public void UpdatePlayerInfo()
    {
        var rent = _eui.PlayerInfo.RentItems.FirstOrDefault(x=>x.ItemId == _itemId);
        var item = _eui.Catalog.Single(x => x.ItemId == _itemId);

        StoreItemBuyButton.Text = rent == null ? $"Купить за {item.Price} монет" : $"Получить";

        if (rent is { ExpirationDate: not null })
        {
            DiscountSubText.Text = "Аренда до: " + rent.ExpirationDate.Value.ToString("g");
        }

        RentButtons.RemoveAllChildren();
        if (rent is { ExpirationDate: not null } or null)
        {
            foreach (var (days,price) in item.PriceRent)
            {
                var btn = new Button();
                btn.OnPressed += _ => { _eui.BuyRentButton(_itemId, days); };
                btn.Text = $"{days} дней за {price} монет";
                RentButtons.AddChild(btn);
            }
        }
        else if (rent is { ExpirationDate: null })
        {
            DiscountSubText.Text = "Навсегда";
        }
    }

    public void UpdateCategory()
    {
        var item = _eui.Catalog.Single(x => x.ItemId == _itemId);

        if (item.GamePrototype != null && _proto.TryIndex<EntityPrototype>(item.GamePrototype, out var entityPrototype))
        {
            StoreItemTexture.Visible = true;
            StoreItemTexture.Texture = _spriteSystem.Frame0(entityPrototype);
            StoreItemName.Text = entityPrototype.Name;
            StoreItemDescription.SetMarkup(entityPrototype.Description);
        }
        else
        {
            StoreItemTexture.Visible = false;
            StoreItemName.Text = item.Name;
            StoreItemDescription.SetMarkup("");
        }
    }

    private void StoreItemBuyButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        _eui.BuyButton(_itemId);
    }
}
