using Content.Shared.DeadSpace.Sponsor;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace.Sponsor.UI;

[GenerateTypedNameReferences]
public sealed partial class SponsorMenu : DefaultWindow, SponsorEui.ISponsorEui
{
    [Dependency] private IPlayerManager _playerManager = default!;
    public SponsorMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Tabs.SetTabTitle(0, "Главная");
        Tabs.SetTabTitle(1, "Подписки");
        Tabs.SetTabTitle(2, "Предметы");
        Tabs.SetTabTitle(3, "Кастомизация");
        //Tabs.OnTabChanged += TabsOnOnTabChanged;

        LoginField.Text = _playerManager.LocalSession?.Name ?? "<UNK>";
        CoinField.Text = "";
        CrystalField.Text = "";

    }
/*
    private void TabsOnOnTabChanged(int obj)
    {
        if (Tabs.GetChild(obj) is SponsorEui.ISponsorEui eui)
        {
            eui.UpdateCategory();
            eui.UpdatePlayerInfo();
        }
    }
*/
    private SponsorEui? currentEui;

    public void SetEui(SponsorEui currentEui)
    {
        this.currentEui = currentEui;
        foreach (var tab in Tabs.Children)
        {
            if (tab is not SponsorEui.ISponsorEui esponsorEui)
                continue;
            esponsorEui.SetEui(currentEui);
        }
    }

    public void UpdateCategory()
    {
        //relay
        foreach (var tab in Tabs.Children)
        {
            if (tab is not SponsorEui.ISponsorEui esponsorEui)
                continue;

            esponsorEui.UpdateCategory();
        }
    }

    public void UpdatePlayerInfo()
    {
        CoinField.Text = currentEui?.PlayerInfo.Coin.ToString();
        CrystalField.Text = currentEui?.PlayerInfo.Crystal.ToString();

        //relay
        foreach (var tab in Tabs.Children)
        {
            if (tab is not SponsorEui.ISponsorEui esponsorEui)
                continue;

            esponsorEui.UpdatePlayerInfo();
        }
    }
}
